# Generated by Django 2.0.6 on 2018-06-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('isrc', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('isrc', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundmatcher.Recording')),
            ],
        ),
    ]
